In [1]:
import numpy as np
import pandas as pd

# Problem 1

In [2]:
a = np.random.randint(1,51, size=(5,4))
print(a)

[[21 37 27 10]
 [12 15 30 28]
 [ 8 43 20 41]
 [50 31 47 39]
 [40 18  1 45]]


In [3]:
anti_diag = []
for i in range(min(a.shape)):
    anti_diag.append(a[i,-i-1])

anti_diag = np.array(anti_diag)
print(anti_diag)
    

[10 30 43 50]


In [4]:
row_max = np.max(a, axis=1)
 
row_max

array([37, 30, 43, 50, 45], dtype=int32)

In [5]:
mean_val = np.mean(a)
mean_val

np.float64(28.15)

In [6]:
new_a = np.array([a[i][j] for i in range(a.shape[0]) for j in range(a.shape[1]) if a[i][j]<=mean_val])

new_a

array([21, 27, 10, 12, 15, 28,  8, 20, 18,  1], dtype=int32)

In [7]:
def numpy_boundary_traversal(matrix):
    rows , cols = matrix.shape
    boundary = []
    boundary.extend(matrix[0, :])
    boundary.extend(matrix[1:rows-1, -1])
    boundary.extend(matrix[rows-1, ::-1])
    boundary.extend(matrix[rows-2:0:-1, 0])

    return np.array(boundary)

boundary = numpy_boundary_traversal(a)
boundary

array([21, 37, 27, 10, 28, 41, 39, 45,  1, 18, 40, 50,  8, 12],
      dtype=int32)

# Problem 2

In [8]:
b = np.random.uniform(0, 10, 20)
b

array([1.99715528, 7.28760813, 2.89204881, 4.12330461, 0.65904635,
       3.52081408, 2.57933678, 5.01468718, 7.24390709, 3.67372029,
       2.05179054, 0.72786258, 1.07479112, 5.07898734, 5.03134528,
       7.18546528, 4.09369332, 0.71834728, 8.24652547, 6.7007052 ])

In [9]:
b = np.round(b,2)
b

array([2.  , 7.29, 2.89, 4.12, 0.66, 3.52, 2.58, 5.01, 7.24, 3.67, 2.05,
       0.73, 1.07, 5.08, 5.03, 7.19, 4.09, 0.72, 8.25, 6.7 ])

In [10]:
print(np.min(b))

0.66


In [11]:
print(np.max(b))

8.25


In [12]:
print(np.median(b))

3.88


In [13]:
for i in range(b.size):
    if b[i] < 5:
        b[i] = b[i]*b[i]

b


array([ 4.    ,  7.29  ,  8.3521, 16.9744,  0.4356, 12.3904,  6.6564,
        5.01  ,  7.24  , 13.4689,  4.2025,  0.5329,  1.1449,  5.08  ,
        5.03  ,  7.19  , 16.7281,  0.5184,  8.25  ,  6.7   ])

In [14]:
def numpy_alternate_sort(array):
    sorted_arr = np.sort(array)
    result = []
    i, j = 0, len(sorted_arr) - 1
    while i <= j:
        result.append(sorted_arr[i])
        if i != j:
            result.append(sorted_arr[j])
        i += 1
        j -= 1
    return np.array(result)

print(numpy_alternate_sort(b))

[ 0.4356 16.9744  0.5184 16.7281  0.5329 13.4689  1.1449 12.3904  4.
  8.3521  4.2025  8.25    5.01    7.29    5.03    7.24    5.08    7.19
  6.6564  6.7   ]


# Problem 3

In [15]:
data = {
    "Name": [f"Student{i}" for i in range(1, 11)],
    "Subject": np.random.choice(["Math", "Science", "English"], size=10),
    "Score": np.random.randint(50, 101, size=10)
}

# Create DataFrame
df = pd.DataFrame(data)
df

Name  Subject  Score
0   Student1  Science     98
1   Student2  English     78
2   Student3     Math     66
3   Student4  Science     88
4   Student5  Science     65
5   Student6     Math     80
6   Student7  Science     83
7   Student8  English     87
8   Student9  Science     92
9  Student10     Math     79

In [16]:
df["Grade"] = ""

def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df["Grade"] = df["Score"].apply(assign_grade)
df

Name  Subject  Score Grade
0   Student1  Science     98     A
1   Student2  English     78     C
2   Student3     Math     66     D
3   Student4  Science     88     B
4   Student5  Science     65     D
5   Student6     Math     80     B
6   Student7  Science     83     B
7   Student8  English     87     B
8   Student9  Science     92     A
9  Student10     Math     79     C

In [17]:
df_sorted = df.sort_values(by="Score", ascending=False)
df_sorted

Name  Subject  Score Grade
0   Student1  Science     98     A
8   Student9  Science     92     A
3   Student4  Science     88     B
7   Student8  English     87     B
6   Student7  Science     83     B
5   Student6     Math     80     B
9  Student10     Math     79     C
1   Student2  English     78     C
2   Student3     Math     66     D
4   Student5  Science     65     D

In [18]:
avg_score = df.groupby("Subject")["Score"].mean()
avg_score

Subject
English    82.5
Math       75.0
Science    85.2
Name: Score, dtype: float64

In [19]:
def pandas_filter_pass(df):
    return df[df["Grade"].isin(["A", "B"])]

df = pandas_filter_pass(df)
df

Name  Subject  Score Grade
0  Student1  Science     98     A
3  Student4  Science     88     B
5  Student6     Math     80     B
6  Student7  Science     83     B
7  Student8  English     87     B
8  Student9  Science     92     A

# Problem 4

In [20]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [21]:
positive = [
  "A masterpiece that redefines cinema",
  "Heartwarming and beautifully crafted",
  "The acting performances are Oscar-worthy",
  "Visually stunning with breathtaking cinematography",
  "Had me on the edge of my seat from start to finish",
  "Perfect blend of humor and emotion",
  "The director's best work yet",
  "A triumph of storytelling",
  "Left me feeling inspired and uplifted",
  "Flawless character development",
  "The soundtrack elevated every scene",
  "A groundbreaking achievement in filmmaking",
  "Powerful and deeply moving",
  "Instant classic that deserves multiple viewings",
  "Brilliantly written dialogue",
  "Perfect pacing that never lags",
  "Emotionally resonant and authentic",
  "The visual effects set a new standard",
  "Captivating from the very first frame",
  "A tour de force performance by the lead",
  "Thought-provoking and profound",
  "The chemistry between actors was electric",
  "Masterful balance of action and drama",
  "Left the entire audience applauding",
  "A cinematic experience like no other",
  "Fresh and innovative storytelling",
  "Perfectly captures the human spirit",
  "The climax left me breathless",
  "Richly detailed world-building",
  "A beautiful love letter to the genre",
  "Elevates the art of filmmaking",
  "The emotional payoff was extraordinary",
  "Every frame could be a painting",
  "A joyful celebration of life",
  "Smart, sophisticated, and satisfying",
  "The best film of the decade",
  "Unforgettable characters you root for",
  "A perfect 10/10 experience",
  "Magical and transportive",
  "Sets a new benchmark for its genre",
  "Deeply satisfying conclusion",
  "The humor landed perfectly every time",
  "A visionary achievement",
  "Pure cinematic poetry",
  "Filled with heart and soul",
  "Remarkable depth and nuance",
  "A rollercoaster of exhilarating emotions",
  "The cinematography was pure artistry",
  "An absolute must-see event",
  "Left me speechless in the best way",
]

negative = [
  "A complete waste of time",
  "Painfully dull and uninspired",
  "The worst screenplay I've ever witnessed",
  "Visual effects looked laughably fake",
  "Plot holes big enough to drive a truck through",
  "Cringeworthy dialogue throughout",
  "An insult to the audience's intelligence",
  "Performances were wooden and lifeless",
  "Directionless mess of a film",
  "Embarrassingly bad CGI",
  "Tone-deaf and offensive portrayal",
  "Pacing slower than watching paint dry",
  "A soulless cash grab",
  "Unbearably pretentious nonsense",
  "Characters were shallow stereotypes",
  "Cliché-ridden from start to finish",
  "The editing gave me a headache",
  "Wasted a talented cast completely",
  "Pointless subplots that go nowhere",
  "Worst movie of the year by far",
  "An incoherent narrative disaster",
  "Emotionally manipulative and hollow",
  "Technically incompetent filmmaking",
  "The soundtrack was distractingly awful",
  "Made me regret buying a ticket",
  "A cynical franchise-killer",
  "Lazy writing at every turn",
  "Visually ugly and poorly shot",
  "Tries too hard and fails miserably",
  "An endurance test for viewers",
  "Completely devoid of originality",
  "The climax was hilariously anticlimactic",
  "Tonally inconsistent whiplash",
  "Overlong by at least an hour",
  "Misguided from concept to execution",
  "Feels like a first draft screenplay",
  "Actors clearly just cashing paychecks",
  "Offensive stereotypes masquerading as characters",
  "A cinematic trainwreck",
  "Makes similar bad films look good",
  "The definition of style over substance",
  "Joyless and plodding",
  "Failed to establish basic coherence",
  "Special effects worse than 90s TV",
  "Dialogue that sounds AI-generated",
  "Zero chemistry between leads",
  "Morally reprehensible messaging",
  "A franchise at rock bottom",
  "Scenes strung together with no purpose",
  "The cinematic equivalent of spam email",
]

In [22]:
len(positive), len(negative)

(50, 50)

In [23]:
reviews = positive + negative
sentiments = ["positive"] * 50 + ["negative"] * 50
df = pd.DataFrame({"Review": reviews, "Sentiment": sentiments})
df

Review Sentiment
0                 A masterpiece that redefines cinema  positive
1                Heartwarming and beautifully crafted  positive
2            The acting performances are Oscar-worthy  positive
3   Visually stunning with breathtaking cinematogr...  positive
4   Had me on the edge of my seat from start to fi...  positive
..                                                ...       ...
95                       Zero chemistry between leads  negative
96                    Morally reprehensible messaging  negative
97                         A franchise at rock bottom  negative
98             Scenes strung together with no purpose  negative
99             The cinematic equivalent of spam email  negative

[100 rows x 2 columns]

In [24]:
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,
)

In [26]:
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.2f}\n")


Test Accuracy: 0.65



In [27]:
def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    return model.predict(review_vec)[0]

test_reviews = [
    "This movie was absolutely wonderful with perfect acting",
    "Terrible waste of time with awful dialogue",
    "The cinematography was breathtaking but the plot was weak",
    "The movie was awesome and fun!"
]

for i, review in enumerate(test_reviews):
    pred = predict_review_sentiment(model, vectorizer, review)
    print(f"Review {i+1}: '{review}' → {pred}")

Review 1: 'This movie was absolutely wonderful with perfect acting' → positive
Review 2: 'Terrible waste of time with awful dialogue' → negative
Review 3: 'The cinematography was breathtaking but the plot was weak' → positive
Review 4: 'The movie was awesome and fun!' → negative
